apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  cluster:
    provider: kubernetes
    clusterName: kubeadm-jenkins-x
    environmentGitOwner: braguru
    gitKind: github
    gitServer: https://github.com
    registry: 774305574116.dkr.ecr.eu-west-1.amazonaws.com
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
  environments:
  - key: dev
    owner: braguru
    repository: jenkins-x
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  webhook: lighthouse