<<<<<<< HEAD
apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  defaults:
    backendType: local
=======
apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
metadata:
  creationTimestamp: null
spec:
  defaults:
    backendType: local
>>>>>>> b937a273d66a74b03f7a016c18fcda27966e06ef
